#+TITLE: Emacs configuration file
#+AUTHOR: Bruce Ravel
#+BABEL: :cache yes
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{inconsolata}
#+PROPERTY: header-args :tangle yes :comments org

* About

This is an Emacs configuration file written in [[http://orgmode.org][Org mode]] following
[[https://github.com/larstvei/dot-emacs][this example]].

I am not doing the fancy bit of having an initial =init.el= whose job
is to tangle this org file, overwriting the initial =init.el=.  That
seems a step too clever.  That said, do the following when setting up
a new machine.  Then exit and restart emacs.  Good to go!

   #+BEGIN_SRC emacs-lisp :tangle no
     ;; We can't tangle without org!
     (require 'org)
     ;; Open the configuration
     (find-file (concat user-emacs-directory "init.org"))
     ;; tangle it
     (org-babel-tangle)
   #+END_SRC



Tangle /this/ file to =.el= when saved.

   #+BEGIN_SRC emacs-lisp
     (defun tangle-init ()
       "If the current buffer is 'init.org' the code-blocks are
     tangled, and the tangled file is compiled."
       (when (equal (buffer-file-name)
                    (expand-file-name (concat user-emacs-directory "init.org")))
         ;; Avoid running hooks when tangling.
         (let ((prog-mode-hook nil))
           (org-babel-tangle)
           (byte-compile-file (concat user-emacs-directory "init.el")))))

     (add-hook 'after-save-hook 'tangle-init)
   #+END_SRC


A file called =local.el= contains customizations specific to a machine.

   #+BEGIN_SRC emacs-lisp
     (add-hook
      'after-init-hook
      (lambda ()
        (let ((local-file (concat user-emacs-directory "local.el")))
          (when (file-exists-p local-file)
            (load-file local-file)))))
   #+END_SRC



* Configurations

** Package

Managing extensions for Emacs is simplified using =package= which is
built in to Emacs 24 and newer. To load downloaded packages we need to
initialize =package=. =cl= is a library that contains many functions from
Common Lisp, and comes in handy quite often, so we want to make sure it's
loaded, along with =package=, which is obviously needed.

   #+BEGIN_SRC emacs-lisp
     (require 'cl)
     (require 'package)
     (package-initialize)
   #+END_SRC

Packages can be fetched from different mirrors, [[http://melpa.milkbox.net/#/][melpa]] is the largest
archive and is well maintained.

   #+BEGIN_SRC emacs-lisp
     (setq package-archives
           '(("gnu" . "http://elpa.gnu.org/packages/")
             ("org" . "http://orgmode.org/elpa/")
             ("MELPA" . "http://melpa.milkbox.net/packages/")))
   #+END_SRC

The configuration assumes that the packages listed below are
installed. To ensure we install missing packages if they are missing.

   #+BEGIN_SRC emacs-lisp
     (let* ((packages
             '(idle-require         ; load elisp libraries while Emacs is idle
               auto-compile         ; automatically compile Emacs Lisp libraries
               magit                ; control Git from Emacs
               markdown-mode        ; major mode for Markdown-formatted files
               mustache-mode        ; mustache templating
               ecb                  ; code browser
               ack-and-a-half       ; ack interface
               org                  ; outline-based notes management and organizer
               powerline            ; rewrite of Powerline
               ))
            ;; Remove all packages already installed
            (packages (remove-if 'package-installed-p packages)))
       (when packages
         (package-refresh-contents)
         (mapcar 'package-install packages)
         ))
   #+END_SRC

** Require

Some features are not loaded by default to minimize initialization
time, so they have to be required (or loaded, if you
will). =require=-calls tends to lead to the largest bottleneck's in a
configuration. =idle-require= delays the =require=-calls to a time
where Emacs is in idle. So this is great for stuff you eventually want
to load, but is not a high priority.

   #+BEGIN_SRC emacs-lisp
     (require 'idle-require)             ; Need in order to use idle-require

     (dolist (feature
              '(auto-compile             ; auto-compile .el files
                ox-latex                 ; the latex-exporter (from org)
                ox-md                    ; Markdown exporter (from org)
                recentf                  ; recently opened files
                tex-mode))               ; TeX, LaTeX, and SliTeX mode commands
       (idle-require feature))

     (setq idle-require-idle-delay 5)
     (idle-require-mode 1)
   #+END_SRC

** defaults

Set some sensible default values

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path "~/dotfiles/emacs")
     (add-to-list 'load-path "~/git/gnuplot-mode/")
     (setq
           inhibit-startup-message t       ; like ... duh!
           scroll-bar-mode (quote right)   ; put the scroll bar on the rght, where Zeus intended it
     )
   #+END_SRC

Some things to turn off

   #+BEGIN_SRC emacs-lisp
     (dolist (mode
              '(tool-bar-mode                ; No toolbars, more room for text.
             ))
       (funcall mode 0))
     (require 'powerline)
     (powerline-default-theme)
   #+END_SRC

And some things to turn on

   #+BEGIN_SRC emacs-lisp
     (dolist (mode
              '(show-paren-mode               ; highlight matching parens
                abbrev-mode                   ; teh --> the
             ))
        (funcall mode 1))
   #+END_SRC

** abbrevs

Set the global abbrev table with some of my least favorite typos

   #+BEGIN_SRC emacs-lisp
     (define-abbrev-table 'global-abbrev-table
       '(
         ("atoim" "atom" nil 1)
         ("atoims" "atoms" nil 1)
         ("teh" "the" nil 2)
        ))
   #+END_SRC


** Theme

This sets my favorite theme, [[https://github.com/juba/color-theme-tangotango][tangotango]], which is not distributed with
emacs.  I keep my own copy in my emacs folder.  This works for
Emacs 24.  This setup was a lot more complicated in Emacs 23

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'custom-theme-load-path "~/dotfiles/emacs")
     (load-theme 'tangotango t)
   #+END_SRC

   #+BEGIN_SRC emacs-lisp :tangle no
     ;(require 'color-theme)
     ;(setq color-theme-load-all-themes nil)

     ;; (require 'color-theme-tangotango) 
     ;; ; (require 'color-theme-bharadwaj)

     ;; ;; select theme - first list element is for windowing system, second is for console/terminal
     ;; ;; Source : http://www.emacswiki.org/emacs/ColorTheme#toc9
     ;; (setq color-theme-choices 
     ;;       '(color-theme-tangotango color-theme-tangotango))
     ;; ;      '(color-theme-bharadwaj color-theme-bharadwaj))

     ;; ;; default-start
     ;; (funcall (lambda (cols)
     ;;     	   (let ((color-theme-is-global nil))
     ;;     	     (eval 
     ;;     	      (append '(if (window-system))
     ;;     		      (mapcar (lambda (x) (cons x nil)) 
     ;;     			      cols)))))
     ;;     	 color-theme-choices)
     
     ;; ;; test for each additional frame or console
     ;; (require 'cl)
     ;; (fset 'test-win-sys 
     ;;       (funcall (lambda (cols)
     ;;     		 (lexical-let ((cols cols))
     ;;     		   (lambda (frame)
     ;;     		     (let ((color-theme-is-global nil))
     ;; 		       ;; must be current for local ctheme
     ;; 		       (select-frame frame)
     ;; 		       ;; test winsystem
     ;; 		       (eval 
     ;; 			(append '(if (window-system frame)) 
     ;; 				(mapcar (lambda (x) (cons x nil)) 
     ;; 					cols)))))))
     ;;     	       color-theme-choices ))
     ;; ;; hook on after-make-frame-functions
     ;; (add-hook 'after-make-frame-functions 'test-win-sys)

     ;; (color-theme-tangotango)
   #+END_SRC



** ECB

Setting this is necessary to get ECB to work with Emacs 24, but it is
bad for Emacs 23.  [[http://stackoverflow.com/questions/8833235/install-ecb-with-emacs-starter-kit-in-emacs-24][See this.]]

   #+BEGIN_SRC emacs-lisp
     (if (= emacs-major-version 24)
         (setq stack-trace-on-error t))
     ;;(add-to-list 'load-path "/home/bruce/dotfiles/emacs/ecb")
     (require 'ecb)
     (setq 
           ecb-history-make-buckets (quote mode)
           ecb-layout-name "leftright1"
           ecb-source-path (quote (("~/git" "git") ("~/TeX" "TeX") ("~/dotfiles" "dotfiles")))
           ecb-tip-of-the-day nil
     )
   #+END_SRC

** perl

Use [[https://github.com/jrockway/cperl-mode][cperl-mode]] instead of the default.  Enable linum-mode.

   #+BEGIN_SRC emacs-lisp
     (defalias 'perl-mode 'cperl-mode)
     (add-hook 'cperl-mode-hook 'linum-mode)
   #+END_SRC


** gnuplot mode

Enable [[https://github.com/bruceravel/gnuplot-mode][gnuplot-mode]] and set the =.gp= extension

   #+BEGIN_SRC emacs-lisp
     (autoload 'gnuplot-mode        "gnuplot"          "gnuplot major mode"                    t)
     (autoload 'gnuplot-make-buffer "gnuplot"          "open a buffer in gnuplot-mode"         t)
     (add-to-list 'auto-mode-alist '("\\.gp$"           . gnuplot-mode))
   #+END_SRC

** markdown mode

Enable [[https://github.com/defunkt/markdown-mode][markdown-mode]] and set the =.md= extension

   #+BEGIN_SRC emacs-lisp
     (autoload 'markdown-mode       "markdown-mode.el" "Major mode for editing Markdown files" t)
     (add-to-list 'auto-mode-alist '("\\.md$" . markdown-mode))
     (add-hook 'markdown-mode-hook
               (lambda ()
                 (auto-fill-mode 1)
               ))
   #+END_SRC

** template toolkit mode

Enable [[https://github.com/davorg/tt-mode][tt-mode]] for Template Toolkit and set the =.tt= extension

   #+BEGIN_SRC emacs-lisp
     (autoload 'tt-mode             "tt-mode"          "Major mode for Template Toolkit files" t)
     (add-to-list 'auto-mode-alist '("\\.tt$"           . tt-mode))
     (add-hook 'tt-mode-hook 'linum-mode)
     (add-hook 'tt-mode-hook 'auto-fill-mode)
   #+END_SRC

** Fortran mode

Linum mode is useful in fortran-mode

   #+BEGIN_SRC emacs-lisp
     (add-hook 'fortran-mode-hook 'linum-mode)
     (setq
           fortran-comment-indent-style (quote relative)
           fortran-continuation-indent 7
     )
   #+END_SRC

** Generic mode

[[http://emacswiki.org/emacs/GenericMode][See this]]

   #+BEGIN_SRC emacs-lisp
     (require 'generic-x)
     (add-to-list 'auto-mode-alist '("\\..*ignore$" . hosts-generic-mode))
   #+END_SRC

** AucTex

This is a skeleton for my most-used Beamer construct in AucTex.  It
makes a columns environment with two 50% width columns.

   #+BEGIN_SRC emacs-lisp
     (define-skeleton beamer-columns-skeleton
       "Insert two columns in a Beamer file"
       nil
       > "\\begin{columns}[T]" \n
       -1 " \\begin{column}{0.5\\linewidth}" \n _ \n
       -3 " \\end{column}" \n
       -1 " \\begin{column}{0.5\\linewidth}" \n \n
       -3 " \\end{column}" \n
       -2 "\\end{columns}")

       (add-hook 'LaTeX-mode-hook 
	  (lambda ()
	    (auto-fill-mode t)
	    (reftex-mode t)
	    (define-key LaTeX-mode-map [(control c) (control \3)] 
	      'beamer-columns-skeleton)))

     (add-to-list 'auto-mode-alist '("\\.tex\\'" . latex-mode))
     (setq TeX-view-program-selection
           (quote (((output-dvi style-pstricks) "dvips and gv")
                    (output-dvi  "xdvi")
                    (output-pdf  "xdg-open")
                    (output-html "xdg-open"))))
   #+END_SRC

Note to self: biblatex

** Ack integration

Use Ack in emacs

   #+BEGIN_SRC emacs-lisp
     (defalias 'ack 'ack-and-a-half)
     (defalias 'ack-same 'ack-and-a-half-same)
     (defalias 'ack-find-file 'ack-and-a-half-find-file)
     (defalias 'ack-find-file-same 'ack-and-a-half-find-file-same)
   #+END_SRC

** mustache-mode

Templating using [[https://mustache.github.io/][mustache]] and/or [[https://github.com/defunkt/pystache][pystache]].

   #+BEGIN_SRC emacs-lisp
     (require 'mustache-mode)
   #+END_SRC

* Key Bindings

A few key bindings programmed into my wrists...

   #+BEGIN_SRC emacs-lisp
     (global-set-key [home]  'beginning-of-buffer)
     (global-set-key [end]   'end-of-buffer)
     (global-set-key "\C-x/" 'point-to-register)
     (global-set-key "\C-xj" 'register-to-point)
     (global-set-key [f12]   'magit-status)
   #+END_SRC
